src/LocalizationInDatabase.Mvc/Controllers/EmployeesController.cs
using AutoMapper;
using LocalizationInDatabase.Mvc.Models.Entities;
using LocalizationInDatabase.Mvc.Services.EntityServices;
using LocalizationInDatabase.Mvc.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace LocalizationInDatabase.Mvc.Controllers;

public class EmployeesController : Controller
{
    private readonly IMapper _mapper;
    private readonly IEmployeeService _employeeService;

    public EmployeesController(IMapper mapper, IEmployeeService employeeService)
    {
        _mapper = mapper;
        _employeeService = employeeService;
    }

    #region Create
    [HttpGet]
    public IActionResult Create()
    {
        return View();
    }

    [HttpPost, ValidateAntiForgeryToken]
    public async Task<IActionResult> CreateAsync(EmployeeViewModel model)
    {
        if (!ModelState.IsValid)
        {
            return View(model);
        }

        var entity = _mapper.Map<Employee>(model);
        await _employeeService.AddAsync(entity);

        if (model.SubmitButton == "redirect")
        {
            return RedirectToAction("List");
        }
        else
        {
            return RedirectToAction("Create");
        }
    }
    #endregion

    #region Read
    [HttpGet]
    public async Task<IActionResult> ListAsync()
    {
        var entities = await _employeeService.ListAsync();
        var model = _mapper.Map<List<EmployeeViewModel>>(entities);

        return View(model);
    }

    [HttpGet]
    public async Task<IActionResult> DetailsAsync(Guid id)
    {
        // Don't exhaust the database if guid has an empty value
        if (id == Guid.Empty)
        {
            return NotFound();
        }

        var entity = await _employeeService.GetAsync(e => e.Id.Equals(id));
        if (entity == null)
        {
            return NotFound();
        }

        var model = _mapper.Map<EmployeeViewModel>(entity);

        return View(model);
    }
    #endregion

    #region Update
    [HttpGet]
    public async Task<IActionResult> EditAsync(Guid id, string? returnUrl)
    {
        // Don't exhaust the database if guid has an empty value
        if (id == Guid.Empty)
        {
            return NotFound();
        }

        var entity = await _employeeService.GetAsync(e => e.Id.Equals(id));
        if (entity == null)
        {
            return NotFound();
        }

        var model = _mapper.Map<EmployeeEditModel>(entity);

        return View(model);
    }

    [HttpPost, ValidateAntiForgeryToken]
    public async Task<IActionResult> EditAsync(Guid id, EmployeeEditModel model, string? returnUrl)
    {
        // Don't exhaust the database if guid has an empty value
        if (id == Guid.Empty)
        {
            return NotFound();
        }

        if (!ModelState.IsValid)
        {
            return View(model);
        }

        var entity = await _employeeService.GetAsync(e => e.Id.Equals(id));
        if (entity == null)
        {
            return NotFound();
        }

        entity = _mapper.Map(model, entity);
        await _employeeService.UpdateAsync(entity);

        if (model.SubmitButton == "redirect")
        {
            if (string.IsNullOrEmpty(returnUrl))
            {
                return RedirectToAction("List");
            }
            else
            {
                return Redirect(returnUrl);
            }
        }
        else
        {
            return RedirectToAction("Edit", new { Id = id, returnUrl });
        }
    }
    #endregion

    #region Delete
    [HttpGet]
    public async Task<IActionResult> DeleteAsync(Guid id, string? returnUrl)
    {
        // Don't exhaust the database if guid has an empty value
        if (id == Guid.Empty)
        {
            return NotFound();
        }

        var entity = await _employeeService.GetAsync(e => e.Id.Equals(id));
        if (entity == null)
        {
            return NotFound();
        }

        await _employeeService.DeleteAsync(entity);

        return string.IsNullOrEmpty(returnUrl) ? RedirectToAction("List") : Redirect(returnUrl);
    }
    #endregion
}

src/LocalizationInDatabase.Mvc/Controllers/LanguagesController.cs
using AutoMapper;
using LocalizationInDatabase.Mvc.Models.Entities;
using LocalizationInDatabase.Mvc.Services.EntityServices;
using LocalizationInDatabase.Mvc.ViewModels;
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Mvc;

namespace LocalizationInDatabase.Mvc.Controllers;

public class LanguagesController : Controller
{
    private readonly IMapper _mapper;
    private readonly ILanguageService _languageService;
    private readonly IStringResourceService _stringResourceService;

    public LanguagesController(IMapper mapper, ILanguageService languageService, IStringResourceService stringResourceService)
    {
        _mapper = mapper;
        _languageService = languageService;
        _stringResourceService = stringResourceService;
    }

    #region Create
    [HttpGet]
    public IActionResult Create()
    {
        return View();
    }

    [HttpPost, ValidateAntiForgeryToken]
    public async Task<IActionResult> CreateAsync(LanguageViewModel model)
    {
        if (!ModelState.IsValid)
        {
            return View(model);
        }

        var language = await _languageService.GetAsync(l => l.Culture.Equals(model.Culture));
        if (language == null)
        {
            var entity = _mapper.Map<Language>(model);
            await _languageService.AddAsync(entity);

            var defaultLanguage = await _languageService.GetAsync(l => l.Culture.Equals("tr-TR"));
            if (defaultLanguage != null)
            {
                var stringResources = await _stringResourceService.ListAsync(s => s.LanguageId.Equals(defaultLanguage.Id));
                if (stringResources != null && stringResources.Any())
                {
                    var newStringResources = stringResources.Select(s => new StringResource()
                    {
                        LanguageId = entity.Id,
                        Name = s.Name,
                        Value = s.Value,
                        IsApproved = s.IsApproved
                    }).ToList();

                    await _stringResourceService.AddRangeAsync(newStringResources);
                }
            }
        }

        if (model.SubmitButton == "redirect")
        {
            return RedirectToAction("List");
        }
        else
        {
            return RedirectToAction("Create");
        }
    }
    #endregion

    #region Read
    [HttpGet]
    public async Task<IActionResult> ListAsync()
    {
        var entities = await _languageService.ListAsync();
        var model = _mapper.Map<List<LanguageViewModel>>(entities);

        return View(model);
    }

    [HttpGet]
    public async Task<IActionResult> DetailsAsync(int id)
    {
        var entity = await _languageService.GetAsync(e => e.Id.Equals(id));
        if (entity == null)
        {
            return NotFound();
        }

        var model = _mapper.Map<LanguageViewModel>(entity);

        return View(model);
    }
    #endregion

    #region Update
    [HttpGet]
    public async Task<IActionResult> EditAsync(int id, string? returnUrl)
    {
        var entity = await _languageService.GetAsync(e => e.Id.Equals(id));
        if (entity == null)
        {
            return NotFound();
        }

        var model = _mapper.Map<LanguageEditModel>(entity);

        return View(model);
    }

    [HttpPost, ValidateAntiForgeryToken]
    public async Task<IActionResult> EditAsync(int id, LanguageEditModel model, string? returnUrl)
    {
        if (!ModelState.IsValid)
        {
            return View(model);
        }

        var culture = await _languageService.GetAsync(e => e.Culture.Equals(model.Culture) && !e.Id.Equals(id));
        if (culture == null)
        {
            var entity = await _languageService.GetAsync(e => e.Id.Equals(id));
            if (entity == null)
            {
                return NotFound();
            }

            entity = _mapper.Map(model, entity);
            await _languageService.UpdateAsync(entity);
        }

        if (model.SubmitButton == "redirect")
        {
            if (string.IsNullOrEmpty(returnUrl))
            {
                return RedirectToAction("List");
            }
            else
            {
                return Redirect(returnUrl);
            }
        }
        else
        {
            return RedirectToAction("Edit", new { Id = id, returnUrl });
        }
    }
    #endregion

    #region Delete
    [HttpGet]
    public async Task<IActionResult> DeleteAsync(int id, string? returnUrl)
    {
        var entity = await _languageService.GetAsync(e => e.Id.Equals(id));
        if (entity == null)
        {
            return NotFound();
        }

        await _languageService.DeleteAsync(entity);

        return string.IsNullOrEmpty(returnUrl) ? RedirectToAction("List") : Redirect(returnUrl);
    }
    #endregion

    [HttpPost, ValidateAntiForgeryToken]
    public IActionResult ChangeLanguage(string cultureCode, string? returnUrl)
    {
        var language = _languageService.GetLanguageByCulture(cultureCode);

        if (language != null)
        {
            var cookieName = CookieRequestCultureProvider.DefaultCookieName;
            var cookieValue = CookieRequestCultureProvider.MakeCookieValue(new RequestCulture(language.Culture, language.Culture));
            var cookieOptions = new CookieOptions { Expires = DateTimeOffset.UtcNow.AddYears(1), SameSite = SameSiteMode.Strict };

            Response.Cookies.Append(cookieName, cookieValue, cookieOptions);
        }

        return string.IsNullOrEmpty(returnUrl) ? RedirectToAction("List") : Redirect(returnUrl);
    }
}

src/LocalizationInDatabase.Mvc/Views/Shared/_CreateButtonsPartial.cshtml
@{
    var routeValues = Context.Request.RouteValues;
    routeValues.TryGetValue("culture", out var culture);
}
<div class="row mt-3">
    <div class="col-md-12">
        <button type="submit" class="btn btn-primary me-2" name="SubmitButton" disabled>
            @Localize[routeValues, "Submit.Button"]
        </button>
        <button type="submit" class="btn btn-primary me-2" name="SubmitButton" value="redirect" disabled>
            @Localize[routeValues, "Submit_and_return_list.Button"]
        </button>
        <a asp-action="List" asp-route-culture="@culture" class="link-dark">@Localize[routeValues, "Return_list.Link"]</a>
    </div>
</div>

src/LocalizationInDatabase.Mvc/Views/Shared/_EditButtonsPartial.cshtml
@{
    var routeValues = Context.Request.RouteValues;
    routeValues.TryGetValue("culture", out var culture);
}
<div class="row mt-3">
    <div class="col-md-12">
        <button type="submit" class="btn btn-primary me-2" name="SubmitButton" disabled>
            @Localize[routeValues, "Submit.Button"]
        </button>
        @if (Context.Request.Query.TryGetValue("returnUrl", out var returnUrl))
        {
            <button type="submit" class="btn btn-primary me-2" name="SubmitButton" value="redirect" disabled>
                @Localize[routeValues, "Submit_and_go_back.Button"]
            </button>
            <a href="@returnUrl" class="link-dark">@Localize[routeValues, "Go_back.Link"]</a>
        }
        else
        {
            <button type="submit" class="btn btn-primary me-2" name="SubmitButton" value="redirect" disabled>
                @Localize[routeValues, "Submit_and_return_list.Button"]
            </button>
            <a asp-action="List" asp-route-culture="@culture" class="link-dark">@Localize[routeValues, "Return_list.Link"]</a>
        }
    </div>
</div>

src/LocalizationInDatabase.Mvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="@Thread.CurrentThread.CurrentUICulture.Name">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Localization Example</title>
    @if (Thread.CurrentThread.CurrentUICulture.TextInfo.IsRightToLeft)
    {
        <link rel="stylesheet" href="~/lib/bootstrap/css/bootstrap.rtl.min.css">
    }
    else
    {
        <link rel="stylesheet" href="~/lib/bootstrap/css/bootstrap.min.css">
    }
    <link rel="stylesheet" href="~/lib/bootstrap-icons/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="~/lib/select2/css/select2.min.css">
    @if (Thread.CurrentThread.CurrentUICulture.TextInfo.IsRightToLeft)
    {
        <link rel="stylesheet" href="~/lib/select2-bootstrap-5-theme/select2-bootstrap-5-theme.rtl.min.css">
    }
    else
    {
        <link rel="stylesheet" href="~/lib/select2-bootstrap-5-theme/select2-bootstrap-5-theme.min.css">
    }
    <link rel="stylesheet" href="~/css/layout.css">
</head>
<body class="min-vh-100 d-flex flex-column" dir="@(Thread.CurrentThread.CurrentUICulture.TextInfo.IsRightToLeft ? "rtl" : "ltr")">
    <header class="bg-dark">
        <nav class="navbar navbar-expand-md navbar-toggleable-md navbar-dark">
            <div class="container-fluid d-flex">
                <a class="navbar-brand flex-grow-1 flex-md-grow-0" asp-action="Index" asp-controller="Home">UI L10n Example</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#header-menu" aria-expanded="false">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div id="header-menu" class="navbar-collapse collapse">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link" asp-action="Index" asp-controller="Home">@Localize["Navbar.Home.Index.Link"]</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-action="List" asp-controller="Employees">@Localize["Navbar.Employees.List.Link"]</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-action="List" asp-controller="Languages">@Localize["Navbar.Languages.List.Link"]</a>
                        </li>
                        <li class="nav-item d-md-none">
                            <form asp-action="ChangeLanguage" asp-route-returnUrl="@Context.Request.Path@Context.Request.QueryString" asp-controller="Languages" method="post">
                                <select name="cultureCode" class="form-select" onchange="this.form.submit()">
                                    @foreach (var culture in Localize.GetCultures())
                                    {
                                        @Html.Raw($"<option value=\"{culture.Name}\" {(Thread.CurrentThread.CurrentUICulture.Name.Equals(culture.Name) ? "selected" : "")}>{culture.NativeName}</option>")
                                    }
                                </select>
                            </form>
                        </li>
                    </ul>
                </div>
                <form asp-action="ChangeLanguage" asp-route-returnUrl="@Context.Request.Path@Context.Request.QueryString" asp-controller="Languages" method="post">
                    <select name="cultureCode" class="form-select d-none d-md-inline" onchange="this.form.submit()">
                        @foreach (var culture in Localize.GetCultures())
                        {
                            @Html.Raw($"<option value=\"{culture.Name}\" {(Thread.CurrentThread.CurrentUICulture.Name.Equals(culture.Name) ? "selected" : "")}>{culture.NativeName}</option>")
                        }
                    </select>
                </form>
            </div>
        </nav>
    </header>
    <div class="container-fluid">
        @await RenderSectionAsync("Submenu", required: false)
    </div>
    <main class="container-fluid flex-grow-1">
        @RenderBody()
    </main>
    <footer class="container-fluid bg-dark text-light py-3 text-end">
        <a href="https://github.com/GormYa/AspnetMvcLocalizationInDatabase" target="_blank">Github</a>
    </footer>
    <script src="~/lib/jquery/jquery.min.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.bundle.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>