src/LocalizationInDatabase.Mvc/Models/Entities/Language.cs
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;
using System.Reflection.Emit;

namespace LocalizationInDatabase.Mvc.Models.Entities;

public class Language
{
    [Key]
    public int Id { get; set; }

    [StringLength(15)]
    [Required]
    public string Culture { get; set; } = null!;

    public ICollection<StringResource> StringResources { get; set; } = null!;
}

public class LanguageConfiguration : IEntityTypeConfiguration<Language>
{
    public void Configure(EntityTypeBuilder<Language> builder)
    {
        var languages = new Language[] {
            new Language { Id = 1, Culture = "tr-TR" },
            new Language { Id = 2, Culture = "en-US" }
        };

        builder.HasData(languages);
    }
}

src/LocalizationInDatabase.Mvc/ViewModels/LanguageViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace LocalizationInDatabase.Mvc.ViewModels;

public class LanguageViewModel
{
    public int Id { get; private set; }

    [Display(Name = "Culture")]
    [MaxLength(15)]
    public string Culture { get; set; } = null!;

    public string? SubmitButton { get; set; }
}

src/LocalizationInDatabase.Mvc/Controllers/LanguagesController.cs
using AutoMapper;
using LocalizationInDatabase.Mvc.Models.Entities;
using LocalizationInDatabase.Mvc.Services.EntityServices;
using LocalizationInDatabase.Mvc.ViewModels;
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Mvc;

namespace LocalizationInDatabase.Mvc.Controllers;

public class LanguagesController : Controller
{
    private readonly IMapper _mapper;
    private readonly ILanguageService _languageService;
    private readonly IStringResourceService _stringResourceService;

    public LanguagesController(IMapper mapper, ILanguageService languageService, IStringResourceService stringResourceService)
    {
        _mapper = mapper;
        _languageService = languageService;
        _stringResourceService = stringResourceService;
    }

    #region Create
    [HttpGet]
    public IActionResult Create()
    {
        return View();
    }

    [HttpPost, ValidateAntiForgeryToken]
    public async Task<IActionResult> CreateAsync(LanguageViewModel model)
    {
        if (!ModelState.IsValid)
        {
            return View(model);
        }

        var language = await _languageService.GetAsync(l => l.Culture.Equals(model.Culture));
        if (language == null)
        {
            var entity = _mapper.Map<Language>(model);
            await _languageService.AddAsync(entity);

            var defaultLanguage = await _languageService.GetAsync(l => l.Culture.Equals("tr-TR"));
            if (defaultLanguage != null)
            {
                var stringResources = await _stringResourceService.ListAsync(s => s.LanguageId.Equals(defaultLanguage.Id));
                if (stringResources != null && stringResources.Any())
                {
                    var newStringResources = stringResources.Select(s => new StringResource()
                    {
                        LanguageId = entity.Id,
                        Name = s.Name,
                        Value = s.Value,
                        IsApproved = s.IsApproved
                    }).ToList();

                    await _stringResourceService.AddRangeAsync(newStringResources);
                }
            }
        }

        if (model.SubmitButton == "redirect")
        {
            return RedirectToAction("List");
        }
        else
        {
            return RedirectToAction("Create");
        }
    }
    #endregion

    #region Read
    [HttpGet]
    public async Task<IActionResult> ListAsync()
    {
        var entities = await _languageService.ListAsync();
        var model = _mapper.Map<List<LanguageViewModel>>(entities);

        return View(model);
    }

    [HttpGet]
    public async Task<IActionResult> DetailsAsync(int id)
    {
        var entity = await _languageService.GetAsync(e => e.Id.Equals(id));
        if (entity == null)
        {
            return NotFound();
        }

        var model = _mapper.Map<LanguageViewModel>(entity);

        return View(model);
    }
    #endregion

    #region Update
    [HttpGet]
    public async Task<IActionResult> EditAsync(int id, string? returnUrl)
    {
        var entity = await _languageService.GetAsync(e => e.Id.Equals(id));
        if (entity == null)
        {
            return NotFound();
        }

        var model = _mapper.Map<LanguageEditModel>(entity);

        return View(model);
    }

    [HttpPost, ValidateAntiForgeryToken]
    public async Task<IActionResult> EditAsync(int id, LanguageEditModel model, string? returnUrl)
    {
        if (!ModelState.IsValid)
        {
            return View(model);
        }

        var culture = await _languageService.GetAsync(e => e.Culture.Equals(model.Culture) && !e.Id.Equals(id));
        if (culture == null)
        {
            var entity = await _languageService.GetAsync(e => e.Id.Equals(id));
            if (entity == null)
            {
                return NotFound();
            }

            entity = _mapper.Map(model, entity);
            await _languageService.UpdateAsync(entity);
        }

        if (model.SubmitButton == "redirect")
        {
            if (string.IsNullOrEmpty(returnUrl))
            {
                return RedirectToAction("List");
            }
            else
            {
                return Redirect(returnUrl);
            }
        }
        else
        {
            return RedirectToAction("Edit", new { Id = id, returnUrl });
        }
    }
    #endregion

    #region Delete
    [HttpGet]
    public async Task<IActionResult> DeleteAsync(int id, string? returnUrl)
    {
        var entity = await _languageService.GetAsync(e => e.Id.Equals(id));
        if (entity == null)
        {
            return NotFound();
        }

        await _languageService.DeleteAsync(entity);

        return string.IsNullOrEmpty(returnUrl) ? RedirectToAction("List") : Redirect(returnUrl);
    }
    #endregion

    [HttpPost, ValidateAntiForgeryToken]
    public IActionResult ChangeLanguage(string cultureCode, string? returnUrl)
    {
        var language = _languageService.GetLanguageByCulture(cultureCode);

        if (language != null)
        {
            var cookieName = CookieRequestCultureProvider.DefaultCookieName;
            var cookieValue = CookieRequestCultureProvider.MakeCookieValue(new RequestCulture(language.Culture, language.Culture));
            var cookieOptions = new CookieOptions { Expires = DateTimeOffset.UtcNow.AddYears(1), SameSite = SameSiteMode.Strict };

            Response.Cookies.Append(cookieName, cookieValue, cookieOptions);
        }

        return string.IsNullOrEmpty(returnUrl) ? RedirectToAction("List") : Redirect(returnUrl);
    }
}

src/LocalizationInDatabase.Mvc/Controllers/StringResourcesController.cs
using AutoMapper;
using LocalizationInDatabase.Mvc.Models.Entities;
using LocalizationInDatabase.Mvc.Services.EntityServices;
using LocalizationInDatabase.Mvc.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Caching.Memory;
using System.Globalization;

namespace LocalizationInDatabase.Mvc.Controllers;

[Route("[controller]")]
public class StringResourcesController : Controller
{
    private readonly IMapper _mapper;
    private readonly ILanguageService _languageService;
    private readonly IStringResourceService _stringResourceService;
    private readonly IMemoryCache _cache;

    public StringResourcesController(IMapper mapper,
        ILanguageService languageService,
        IStringResourceService stringResourceService,
        IMemoryCache cache)
    {
        _mapper = mapper;
        _languageService = languageService;
        _stringResourceService = stringResourceService;
        _cache = cache;
    }

    #region Create
    [HttpGet("{culture}/[action]")]
    public async Task<IActionResult> CreateAsync(string culture)
    {
        var language = await _languageService.GetAsync(l => l.Culture.Equals(culture));
        if (language == null)
        {
            return NotFound();
        }

        ViewBag.CultureInfo = new CultureInfo(language.Culture);
        ViewBag.Language = _mapper.Map<LanguageViewModel>(language);

        return View();
    }

    [HttpPost("{culture}/[action]"), ValidateAntiForgeryToken]
    public async Task<IActionResult> CreateAsync(string culture, StringResourceEditModel model)
    {
        var language = await _languageService.GetAsync(l => l.Culture.Equals(culture));
        if (language == null)
        {
            return NotFound();
        }

        if (!ModelState.IsValid)
        {
            ViewBag.CultureInfo = new CultureInfo(language.Culture);
            ViewBag.Language = _mapper.Map<LanguageViewModel>(language);

            return View(model);
        }

        var stringResource = await _stringResourceService.GetAsync(s => s.Name.Equals(model.Name) && s.LanguageId.Equals(language.Id));
        if (stringResource == null)
        {
            var entity = _mapper.Map<StringResource>(model);
            entity.LanguageId = language.Id;

            await _stringResourceService.AddAsync(entity);
        }

        if (model.SubmitButton == "redirect")
        {
            return RedirectToAction("List", new { Culture = culture });
        }
        else
        {
            return RedirectToAction("Create", new { Culture = culture });
        }
    }
    #endregion

    #region Read
    [HttpGet("{culture}/[action]")]
    public async Task<IActionResult> ListAsync(string culture)
    {
        var language = await _languageService.GetAsync(l => l.Culture.Equals(culture));
        if (language == null)
        {
            return NotFound();
        }

        ViewBag.CultureInfo = new CultureInfo(language.Culture);
        ViewBag.Language = _mapper.Map<LanguageViewModel>(language);

        var entities = await _stringResourceService.ListAsync(sr => sr.LanguageId.Equals(language.Id),
            include: sr => sr.Include(i => i.Language),
            orderBy: sr => sr.OrderBy(o => o.IsApproved).ThenBy(o => o.Name));
        var model = _mapper.Map<List<StringResourceViewModel>>(entities);

        return View(model);
    }

    [HttpGet("{culture}/[action]/{id}")]
    public async Task<IActionResult> DetailsAsync(string culture, int id)
    {
        var language = await _languageService.GetAsync(l => l.Culture.Equals(culture));
        if (language == null)
        {
            return NotFound();
        }

        ViewBag.CultureInfo = new CultureInfo(language.Culture);
        ViewBag.Language = _mapper.Map<LanguageViewModel>(language);

        var entity = await _stringResourceService.GetAsync(e => e.Id.Equals(id));
        if (entity == null)
        {
            return NotFound();
        }

        var model = _mapper.Map<StringResourceViewModel>(entity);

        return View(model);
    }
    #endregion

    #region Update
    [HttpGet("{culture}/[action]/{id}")]
    public async Task<IActionResult> EditAsync(string culture, int id, string? returnUrl)
    {
        var language = await _languageService.GetAsync(l => l.Culture.Equals(culture));
        if (language == null)
        {
            return NotFound();
        }

        ViewBag.CultureInfo = new CultureInfo(language.Culture);
        ViewBag.Language = _mapper.Map<LanguageViewModel>(language);

        var entity = await _stringResourceService.GetAsync(e => e.Id.Equals(id));
        if (entity == null)
        {
            return NotFound();
        }

        var model = _mapper.Map<StringResourceEditModel>(entity);

        return View(model);
    }

    [HttpPost("{culture}/[action]/{id}"), ValidateAntiForgeryToken]
    public async Task<IActionResult> EditAsync(string culture, int id, StringResourceEditModel model, string? returnUrl)
    {
        var language = await _languageService.GetAsync(l => l.Culture.Equals(culture));
        if (language == null)
        {
            return NotFound();
        }

        if (!ModelState.IsValid)
        {
            ViewBag.CultureInfo = new CultureInfo(language.Culture);
            ViewBag.Language = _mapper.Map<LanguageViewModel>(language);

            return View(model);
        }

        var stringResource = await _stringResourceService.GetAsync(s => s.Name.Equals(model.Name) && s.LanguageId.Equals(language.Id) && !s.Id.Equals(id));
        if (stringResource == null)
        {
            var entity = await _stringResourceService.GetAsync(e => e.Id.Equals(id));
            if (entity == null)
            {
                return NotFound();
            }

            entity = _mapper.Map(model, entity);
            entity.LanguageId = language.Id;
            await _stringResourceService.UpdateAsync(entity);

            _cache.Remove($"stringResource_{entity.Name}_{language.Id}");
        }

        if (model.SubmitButton == "redirect")
        {
            if (string.IsNullOrEmpty(returnUrl))
            {
                return RedirectToAction("List", new { Culture = culture });
            }
            else
            {
                return Redirect(returnUrl);
            }
        }
        else
        {
            return RedirectToAction("Edit", new { Culture = culture, Id = id, returnUrl });
        }
    }
    #endregion

    #region Delete
    [HttpGet("{culture}/[action]/{id}")]
    public async Task<IActionResult> DeleteAsync(string culture, int id, string? returnUrl)
    {
        var language = await _languageService.GetAsync(l => l.Culture.Equals(culture));
        if (language == null)
        {
            return NotFound();
        }

        ViewBag.CultureInfo = new CultureInfo(language.Culture);
        ViewBag.Language = _mapper.Map<LanguageViewModel>(language);

        var entity = await _stringResourceService.GetAsync(e => e.Id.Equals(id));
        if (entity == null)
        {
            return NotFound();
        }

        _cache.Remove($"stringResource_{entity.Name}_{language.Id}");
        await _stringResourceService.DeleteAsync(entity);

        return string.IsNullOrEmpty(returnUrl) ? RedirectToAction("List", new { Culture = culture }) : Redirect(returnUrl);
    }
    #endregion
}

src/LocalizationInDatabase.Mvc/Views/Languages/Create.cshtml
@using System.Globalization
@model LanguageViewModel
@{
    ViewData["Title"] = @Localize["Languages.Create.Title"];
    var addedCultures = Localize.GetCultures();
    var availableCultures = CultureInfo.GetCultures(CultureTypes.AllCultures)
        .Where(c => !c.Name.Equals(string.Empty) && !addedCultures.Contains(c))
        .OrderBy(d => d.DisplayName);
}

<h3 class="mb-3">@Localize["Languages.Create.Heading"]</h3>
<form method="post" data-track="form">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="row">
        <div class="col-md-4">
            <div class="form-floating">
                <select name="Culture" class="form-select" aria-label="@Html.DisplayNameFor(model => model.Culture)">
                    @foreach (var culture in availableCultures)
                    {
                        @Html.Raw($"<option value=\"{culture.Name}\" {(Thread.CurrentThread.CurrentUICulture.Name.Equals(culture.Name) ? "selected" : "")}>{culture.DisplayName} - {culture.Name}</option>")
                    }
                </select>
                <label asp-for="Culture"></label>
                <span asp-validation-for="Culture" class="text-danger"></span>
            </div>
        </div>
    </div>
    <partial name="_CreateButtonsPartial" />
</form>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}
    @section Submenu{
    <div class="row py-3 align-items-center">
        <div class="col-md-6 mb-2 mb-md-0">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb m-0">
                    <li class="breadcrumb-item">
                        <a asp-action="Index" asp-controller="Home">@Localize["Breadcrumb.Home.Index"]</a>
                    </li>
                    <li class="breadcrumb-item">
                        <a asp-action="List">@Localize["Breadcrumb.Languages.List"]</a>
                    </li>
                    <li class="breadcrumb-item active" aria-current="page">
                        @Localize["Breadcrumb.Languages.Create"]
                    </li>
                </ol>
            </nav>
        </div>
        <div class="col-md-6 text-end">
            <a asp-action="List" class="btn btn-dark">@Localize["Submenu.Languages.List.Button"]</a>
        </div>
    </div>
}

src/LocalizationInDatabase.Mvc/Views/Languages/Edit.cshtml
@using System.Globalization
@model LanguageEditModel
@{
    var modelCulture = new CultureInfo(Model.Culture);

    ViewData["Title"] = @Localize["Languages.Edit.Title", arguments: modelCulture.DisplayName];

    var addedCultures = Localize.GetCultures();
    var availableCultures = CultureInfo.GetCultures(CultureTypes.AllCultures)
        .Where(c => (!c.Name.Equals(string.Empty) && !addedCultures.Contains(c)) || c.Name.Equals(Model.Culture))
        .OrderBy(d => d.DisplayName);
}

<h3 class="mb-3">@Localize["Languages.Edit.Heading", arguments: modelCulture.DisplayName]</h3>
<form method="post" data-track="form">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="row">
        <div class="col-md-4">
            <div class="form-floating">
                <select name="Culture" class="form-select" aria-label="@Html.DisplayNameFor(model => model.Culture)">
                    @foreach (var culture in availableCultures)
                    {
                        @Html.Raw($"<option value=\"{culture.Name}\" {(culture.Name.Equals(Model.Culture) ? "selected" : "")}>{culture.DisplayName} - {culture.Name}</option>")
                    }
                </select>
                <label asp-for="Culture"></label>
                <span asp-validation-for="Culture" class="text-danger"></span>
            </div>
        </div>
    </div>
    <partial name="_EditButtonsPartial" />
</form>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}
    @section Submenu{
    <div class="row py-3 align-items-center">
        <div class="col-md-6 mb-2 mb-md-0">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb m-0">
                    <li class="breadcrumb-item">
                        <a asp-action="Index" asp-controller="Home">@Localize["Breadcrumb.Home.Index"]</a>
                    </li>
                    <li class="breadcrumb-item">
                        <a asp-action="List">@Localize["Breadcrumb.Languages.List"]</a>
                    </li>
                    <li class="breadcrumb-item">
                        <a asp-action="Details" asp-route-id="@Context.GetRouteValue("id")">@Localize["Breadcrumb.Languages.Details", arguments: modelCulture.DisplayName]</a>
                    </li>
                    <li class="breadcrumb-item active" aria-current="page">
                        @Localize["Breadcrumb.Languages.Edit"]
                    </li>
                </ol>
            </nav>
        </div>
        <div class="col-md-6 text-end">
            <a asp-action="List" class="btn btn-dark">@Localize["Submenu.Languages.List.Button"]</a>
        </div>
    </div>
}

src/LocalizationInDatabase.Mvc/Views/Languages/List.cshtml
@using System.Globalization
@model IEnumerable<LanguageViewModel>
@{
    ViewData["Title"] = Localize["Languages.List.Title"];
}

<h3 class="mb-3">@Localize["Languages.List.Heading"]</h3>
@if (Model.Count() == 0)
{
    <p>
        @Localize["Languages.List.No_languages"]
    </p>
}
else
{
    <div class="table-responsive">
        <table class="table table-light table-borderless table-striped align-middle mb-0">
            <thead>
                <tr>
                    <th class="align-middle">
                        @Localize["Languages.List.Th_name"]
                    </th>
                    <th class="align-middle">
                        @Localize["Languages.List.Th_culture"]
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @CultureInfo.GetCultureInfo(item.Culture).DisplayName
                        </td>
                        <td>
                            @item.Culture
                        </td>
                        <td class="text-end">
                            <a asp-action="List" asp-controller="StringResources" asp-route-culture="@item.Culture">@Localize["Languages.List.StringResources.Link"]</a> |
                            <a asp-action="Details" asp-route-id="@item.Id">@Localize["Languages.List.Details.Link"]</a> |
                            <a asp-action="Edit" asp-route-id="@item.Id">@Localize["Languages.List.Edit.Link"]</a> |
                            <a asp-action="Delete" asp-route-id="@item.Id" class="link-danger">@Localize["Languages.List.Delete.Link"]</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
}
@section Submenu{
    <div class="row py-3 align-items-center">
        <div class="col-md-6 mb-2 mb-md-0">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb m-0">
                    <li class="breadcrumb-item">
                        <a asp-action="Index" asp-controller="Home">@Localize["Breadcrumb.Home.Index"]</a>
                    </li>
                    <li class="breadcrumb-item active" aria-current="page">
                        @Localize["Breadcrumb.Languages.List"]
                    </li>
                </ol>
            </nav>
        </div>
        <div class="col-md-6 text-end">
            <a asp-action="Create" class="btn btn-primary">@Localize["Submenu.Languages.Create.Button"]</a>
        </div>
    </div>
}